### PR TITLE
feat: support options.env to specific server env

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg/pull/3430 要用到，不通过环境变量来设置了

**Comment by atian25** [comment]
https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js#L144

这个地方，是否也需要放通 env 参数。

**Comment by dead-horse** [comment]
egg-cluster 里面还是用到了 EGG_SERVER_ENV，cluster 模式先不动吧

**Comment by dead-horse** [comment]
4.14.0

**Pull request merged**
