### PR TITLE
fix: check whether controller exists

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

cause by https://github.com/eggjs/egg-core/pull/125/files#diff-8c3b17be5fc29672ba311e100af6bbacR316

Controller instance check will delay.

### CODE REVIEW

**Comment by atian25** [comment]
@popomore 发个版本吧

**Comment by popomore** [comment]
我还有一个改动

**Comment by dead-horse** [comment]
额，这个已经和 #140 一起发掉了

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/pull/136

说的是这个吧，单独发就好了。

**Pull request merged**
