### PR TITLE
chore: add pkg.files

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by atian25** [comment]
常用的一次性加全好了. https://github.com/eggjs/egg-boilerplate-plugin/blob/master/boilerplate/package.json#L13

**Comment by fengmk2** [comment]
不要，还是按需配置。

+1

**Comment by popomore** [comment]
发个 fix

**Comment by popomore** [comment]
+ egg-core@1.0.1

**Pull request merged**
