### PR TITLE
feat: loadUnit should exports name

### PR DESCRIPTION
**Pull request by atian25**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

close https://github.com/eggjs/egg/issues/2767

### CODE REVIEW

**Comment by atian25** [comment]
ping @popomore

**Comment by popomore** [comment]
wait https://github.com/eggjs/egg-core/pull/169

**Comment by atian25** [comment]
4.9.0

**Comment by atian25** [comment]
有个 bug，先回滚 dist-tags 了

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/pull/174

**Pull request merged**
