### PR TITLE
refactor: use template literals in lib/utils/index.js

### PR DESCRIPTION
**Pull request by m31271n**
##### Checklist

- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

+ lib/utils/index.js

##### Description of change

+ use template literals in lib/utils/index.js

### CODE REVIEW

**Comment by atian25** [comment]
it just a `style`, not big enough to be `refactor`

**Comment by m31271n** [comment]
@atian25 Get it. By the way, where to find avaliable commit types like `style`?

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/contributing.html#commit-提交规范

**Comment by m31271n** [comment]
Thank you.

**Pull request merged**
