### PR TITLE
fix: context loader cache independent in each request

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

ContextLoader

##### Description of change

fix cache

### CODE REVIEW

**Comment by atian25** [comment]
also need to pick to 1.x

**Comment by dead-horse** [comment]
1.x 还有谁在用？

**Comment by atian25** [comment]
@dead-horse egg 之前的版本有在用 1.x 的吧?

**Comment by fengmk2** [comment]
2.0.1

**Comment by dead-horse** [comment]
@atian25 之前版本的先不考虑了吧

**Pull request merged**
