### PR TITLE
fix: don't assert config.proxy

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

conflict with https://github.com/eggjs/egg/pull/231

### CODE REVIEW

**Comment by atian25** [comment]
+1

**Comment by popomore** [comment]
我发个版本

**Comment by popomore** [comment]
+ egg-core@1.5.1

**Comment by popomore** [comment]
egg 用例可能也会挂

**Pull request merged**
