### PR TITLE
refactor: warn only for redefine the same package

### PR DESCRIPTION
**Pull request by popomore**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

##### Affected core subsystem(s)

loadPlugin

### CODE REVIEW

**Comment by fengmk2** [comment]
+1

将 ci 修复跑过就合并了。

**Comment by popomore** [comment]
感觉 should 在 7 下有问题，我改成 assert

**Comment by atian25** [comment]
回头 should 是不是见一个改一个 @_@

**Comment by fengmk2** [comment]
能改 assert 就改了吧。chair 的所有新测试我都改了。。。

**Comment by gxcsoccer** [comment]
+1

**Comment by popomore** [comment]
@fengmk2

**Comment by popomore** [comment]
+ egg-core@1.3.3

**Pull request merged**
