### PR TITLE
refactor: ensure treat function app.js as configDidLoad

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

把原来的 app.js 当做 configDidLoad

### CODE REVIEW

**Comment by dead-horse** [comment]
这样改造任何一个插件的 app.js 到 lifecycle 模型才不会有兼容性问题

**Comment by killagu** [comment]
`configDidLoad` 执行顺序的测试加一个吧。

**Comment by dead-horse** [comment]
测试优化了一下

**Comment by fengmk2** [comment]
Bugfix release

**Comment by fengmk2** [comment]
4.10.1

**Pull request merged**
