### PR TITLE
feat: should find the $root/node_modules under npm3

### PR DESCRIPTION
**Pull request by zhennann**
Should find the $root/node_modules under npm3, as $root maybe not $cwd

##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by popomore** [comment]
It should be supported, can you give me a demo that show how do you use.

**Comment by zhennann** [comment]
@popomore 

### scenario
repo: egg-scripts v2.1.1
file: ./lib/cmd/start.js
line: 124

``` javascript
    const options = {
      cwd: baseDir,
      execArgv: context.execArgv,
      env,
      stdio: 'inherit',
      detached: false,
    };
```
so that, if project specified the `baseDir` argument in the `egg-scripts` command line, the `$cwd` will be same as `$baseDir`.  In this scenario, will not find plugins under npm3.

### demo one
see directory `egg-core/test/fixtures/flat-npm3` and file `egg-core/test/egg.test.js` line 445.
``` javascript
  describe('flat npm3', () => {
    let app;
    before(() => {
      mm(process, 'cwd', () => utils.getFilepath('flat-npm3/base-dir'));
      const EggApplication = require('./fixtures/flat-npm3/node_modules/egg');
      app = utils.createApp('flat-npm3/base-dir', {
        Application: EggApplication,
      });
      app.loader.loadPlugin();
      return app.ready();
    });
    after(() => app.close());

    it('should has plugin of package', () => {
      assert(app.plugins.package.name === 'package');
    });
  });
```
### demo two
create a project of `EggBorn.js`, and `npm install` by the flat way.
`npm run start:backend` will work normally with `egg-scripts v1.2.0`, while  will not work with `egg-scripts v2.1.1`.

**Comment by atian25** [comment]
could you provide a test repos?

**Comment by fengmk2** [comment]
`flat-npm3/base-dir` is the baseDir, and `node_modules` should be under the `flat-npm3/base-dir/node_modules` location.

-1 for this change.

**Comment by zhennann** [comment]
Please see the test repo : [egg-core-pull-129](https://github.com/zhennann/egg-core-pull-129)

In some full stack project, the egg baseDir may be the subdir of project root path. so, when `npm install` under the root path, the `node_modules` will be `root/node_modules`, not `eggbarDir/node_modules`.

# egg-core-pull-129

## Installation

``` bash
$ cd egg-core-pull-129
$ npm install
```

## Configure MySQL

Please configure mysql connection parameters. (empty database just does well)

Edit the file: `src/backend/config/config.default.js`
``` javascript
  // mysql
  config.mysql = {
    clients: {
      // donot change the name  
      __ebdb: {
        host: '127.0.0.1',
        port: '3306',
        user: 'travis',
        password: '',
        database: 'egg-born',
      },
    },
  };
```

## Run

### Start Backend Dev Service
``` bash
$ npm run dev:backend
```

This will work normallly.

### Start Backend Prod Service
``` bash
$ npm run start:backend
```

This will not work, and throw such error:
> throw new Error(`Can not find plugin ${name} in "${lookupDirs.join(', ')}"`);
>   egg-core-pull-129/node_modules/egg-core/lib/loader/mixin/plugin.js:345

**Comment by popomore** [comment]
It failed because of the directory, egg-core will try to find the module in process.cwd(), but egg-scripts has set it as baseDir.

@atian25 maybe we can delete it https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js#L125

**Comment by atian25** [comment]
sure, with https://github.com/eggjs/egg/issues/1644

**Comment by zhennann** [comment]
@popomore  fine. May I submit pr (remove line125 and add a test fixture) to egg-scripts.

**Comment by atian25** [comment]
sure, welcome

**Comment by zhennann** [comment]
ok

**Pull request closed without merging**
