### PR TITLE
feat: make app middlewares also support enable

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by dead-horse** [comment]
@popomore 这样的话发布的时候内部应用迁移时要注意这个，如果定义的中间件有 enable/match/ignore 的参数的话迁移脚本要给警告。

**Comment by fengmk2** [comment]
+1

**Comment by popomore** [comment]
+1

**Comment by popomore** [comment]
@dead-horse 已经记录了

**Comment by popomore** [comment]
+ egg-core@1.3.0

**Pull request merged**
