### PR TITLE
feat: add toPromise and toAsyncFunction

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by dead-horse** [comment]
再考虑一下是不是适合放在这里，感觉放 helper 也不合适。

**Comment by popomore** [comment]
放 app 比较好，所有地方都能拿到

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/1564

**Comment by dead-horse** [comment]
恩，这个先合并发布

**Comment by dead-horse** [comment]
3.6.0

**Pull request merged**
