### PR TITLE
deps: use egg router 2.0.0

### PR DESCRIPTION
**Pull request by fengmk2**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
等等 egg 发个版本即可。

**Comment by fengmk2** [comment]
link 到 egg 已经跑过。

**Comment by dead-horse** [comment]
egg 已经发了

**Comment by dead-horse** [comment]
4.14.1

**Pull request merged**
