### PR TITLE
refactor: support config/env instead of config/serverEnv

### PR DESCRIPTION
**Pull request by dead-horse**
##### Checklist

- [] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

从 `config/env` 文件读取环境，对用户去除 `serverEnv` 的概念

### CODE REVIEW

**Comment by fengmk2** [comment]
@dead-horse email 不对 
image

**Comment by popomore** [comment]
Win 报的错看不懂

**Comment by atian25** [comment]
https://github.com/node-modules/common-bin/blob/master/lib/helper.js#L25

```
4 Internal JavaScript Evaluation Failure - The JavaScript source code internal in Node.js's bootstrapping process failed to return a function value when evaluated. This is extremely rare, and generally can only happen during development of Node.js itself.
```

**Comment by atian25** [comment]
看来应该召唤 @JacksonTian 

https://github.com/node-modules/common-bin/blob/master/lib/helper.js#L25

https://nodejs.org/api/process.html#process_exit_codes
> 4 Internal JavaScript Evaluation Failure - The JavaScript source code internal in Node.js's bootstrapping process failed to return a function value when evaluated. This is extremely rare, and generally can only happen during development of Node.js itself.

**Comment by fengmk2** [comment]
1.4.0

**Pull request merged**
