### PR TITLE
style: spelling mistakes，orginal -> original

### PR DESCRIPTION
**Pull request by AnzerWall**
1st pr, just test

##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by dead-horse** [comment]
👍

**Comment by fengmk2** [comment]
the commit author is not github user account ...

image

**Comment by AnzerWall** [comment]
QAQ 什么意思，是账号啊，我做错了什么

**Comment by AnzerWall** [comment]
QAQ 什么意思，是账号啊，我做错了什么


------

好神奇，一定是大小写的锅！

**Pull request merged**
